# Generated by Django 4.2.1 on 2023-05-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(upload_to='profile_photo/'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='content_url',
            field=models.FileField(upload_to='stories/pdfs/'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='cover_image',
            field=models.ImageField(upload_to='stories/covers/'),
        ),
    ]
