# Generated by Django 4.2.1 on 2023-06-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_profile_id_comment_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
